# Generated by Django 4.2.11 on 2024-04-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cart_productid"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="useremail",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
